### ISSUE TITLE
Add support for command line arguments please

### ISSUE THREAD

**Issue by JnCrMx** [D-VAmpire/WiFi_QR_LaTeX#6]
For example it would be awesome to be able to use the script this like:
```bash
./run.sh --ssid foo --psk bar --output baz.pdf
```
For that ``getopt(1)`` might be useful.

It might also be good to be able to supply them with enviornment variables.

**Comment by D-VAmpire** [comment]
_Notes to commit:_ 

The ENV variables are named `ssid`, `pw`, and `outfile`.
If both are supplied, the script will now use `--ssid` and `--pw` arguments (or `-s`, `--name` and `-p`, `--pass`, `--psk`, `--password` respectively) instead of anything else as its input. This still overwrites the credentials file since this file is considered temporary anyway. The CLI arg `--outfile` (or `--out`, `-o`) is available as well (as requested) – if unset, then `${ssid}.pdf` is used as the output file name instead.
